addr = "0.0.0.0:8080"
hello_wav = "hello.wav"

[tts]
platform = "openai"
url = "https://api.groq.com/openai/v1/audio/speech"
model = "playai-tts"
api_key = "gsk_ABCD"
voice = "Fritz-PlayAI"

[asr]
platform = "openai"
url = "https://api.groq.com/openai/v1/audio/transcriptions"
api_key = "gsk_ABCD"
model = "whisper-large-v3"
lang = "en"
prompt = "Hello\n你好\n(noise)\n(bgm)\n(silence)\n"
# Requires a local Silero VAD server: https://github.com/second-state/silero_vad_server
# Default port is 8000, but some setups may use 9093. Update the port below if needed.
vad_url = "http://localhost:8000/v1/audio/vad"
# vad_realtime_url = "ws://localhost:8000/v1/audio/realtime_vad"

[llm]
platform = "openai_chat"
url = "https://api.groq.com/openai/v1/chat/completions"
api_key = "gsk_ABCD"
model = "openai/gpt-oss-20b"
history = 5

[[llm.sys_prompts]]
role = "system"
content = """
You are a helpful assistant. Answer truthfully and concisely.
"""
