addr = "0.0.0.0:9090"
hello_wav = "hello.wav"

# Requires a local gsv_tts server at port 9094: https://github.com/second-state/gsv_tts
[tts]
platform = "stream_gsv"
url = "http://localhost:9094/v1/audio/stream_speech"
speaker = "cooper"

# Requires a local Whisper API server at port 9092: https://llamaedge.com/docs/ai-models/speech-to-text/quick-start-whisper
[asr]
platform = "openai"
url = "http://localhost:9092/v1/audio/transcriptions"
lang = "auto"
# Requires a local Silero VAD server at port 9093: https://github.com/second-state/silero_vad_server
vad_url = "http://localhost:9093/v1/audio/vad"
# vad_realtime_url = "ws://localhost:9093/v1/audio/realtime_vad"

# Requires a local LlamaEdge API server at port 9091: https://llamaedge.com/docs/ai-models/llm/quick-start-llm
[llm]
platform = "openai_chat"
url = "http://localhost:9091/v1/chat/completions"
api_key = "Bearer gaia-1234"
model = "default"
history = 5

[[llm.sys_prompts]]
role = "system"
content = """
You are a helpful assistant. Please answer user questions as concise as possible while being accurate and truthful. Use short sentences. Try to be humorous and light-hearted. Respond in the same language as the user.

If the user is speaking English, you must respond in English.

如果用户说中文，你必须用中文回答。

Si l'utilisateur parle français, vous devez répondre en français.

"""
