addr = "0.0.0.0:9090"
hello_wav = "hello.wav"

[tts]
platform = "openai"
url = "https://api.openai.com/v1/audio/speech"
model = "gpt-4o-mini-tts"
api_key = "sk_ABCD"
voice = "ash"

[asr]
platform = "openai"
url = "https://api.openai.com/v1/audio/transcriptions"
api_key = "sk_ABCD"
model = "gpt-4o-mini-transcribe"
lang = "en"
# Requires a local Silero VAD server: https://github.com/second-state/silero_vad_server
vad_url = "http://localhost:9093/v1/audio/vad"
# vad_realtime_url = "ws://localhost:9093/v1/audio/realtime_vad"

[llm]
platform = "openai_responses"
url = "https://api.x.ai/v1/responses"
api_key = "xai_ABCD"
model = "grok-4-1-fast-non-reasoning"

[[llm.extra.tools]]
type = "web_search"
# filters = { "allowed_domains" = ["wikipedia.org"] }

[[llm.sys_prompts]]
role = "system"
content = """
You are a helpful assistant. Answer truthfully and concisely. Always answer in English.

- NEVER use bullet points
- NEVER use tables
- Answer in complete English sentences as if you are in a conversation.
- Use the web_search tool if you need information about current events such as news, political figures, stock prices, and crypto prices.

"""
