addr = "0.0.0.0:8080"
hello_wav = "hello.wav"

# Requires a local GPT-SoVITS server at port 9094: https://github.com/second-state/gsv_tts
[tts]
platform = "stream_gsv"
url = "http://localhost:9094/v1/audio/stream_speech"
speaker = "texan"

[asr]
platform = "openai"
url = "https://api.openai.com/v1/audio/transcriptions"
api_key = "sk_ABCD"
model = "gpt-4o-mini-transcribe"
lang = "en"
# Optional: requires a local Silero VAD server: https://github.com/second-state/silero_vad_server
vad_url = "http://localhost:9093/v1/audio/vad"
# vad_realtime_url = "ws://localhost:9093/v1/audio/realtime_vad"

[llm]
platform = "openai_chat"
url = "https://api.openai.com/v1/chat/completions"
api_key = "sk_ABCD"
model = "gpt-5-nano"
history = 5

[[llm.sys_prompts]]
role = "system"
content = """
You are a helpful assistant. Answer truthfully and concisely. Always answer in English.

- NEVER use bullet points
- NEVER use tables
- Answer in complete English sentences as if you are in a conversation.

"""
