addr = "0.0.0.0:9090"
hello_wav = "hello.wav"

[tts]
platform = "Groq"
model = "playai-tts"
api_key = "gsk_ABCD"
voice = "Fritz-PlayAI"

[asr]
platform = "whisper"
url = "https://api.groq.com/openai/v1/audio/transcriptions"
api_key = "gsk_ABCD"
model = "whisper-large-v3"
lang = "en"
prompt = "Hello\n你好\n(noise)\n(bgm)\n(silence)\n"
# Requires a local Silero VAD server: https://github.com/second-state/silero_vad_server
vad_url = "http://localhost:9093/v1/audio/vad"
# vad_realtime_url = "ws://localhost:9093/v1/audio/realtime_vad"

[llm]
platform = "chat"
url = "https://api.groq.com/openai/v1/chat/completions"
api_key = "gsk_ABCD"
model = "openai/gpt-oss-20b"
history = 5

[[llm.sys_prompts]]
role = "system"
content = """
You are a helpful assistant. Answer truthfully and concisely.
"""
